import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { runAnalysis, generatePlan } from '../utils/api';
import { useGoogleLogin } from '@react-oauth/google';

export default function Analysis({
    competitors,
    activeCompetitorId,
    onSelectCompetitor,
    analysisDataMap,
    planDataMap,
    onAnalysisComplete,
    onPlanComplete,
}) {
    const [analyzing, setAnalyzing] = useState(false);
    const [analyzingId, setAnalyzingId] = useState(null);
    const [planning, setPlanning] = useState(false);
    const [error, setError] = useState('');
    const [analyzingAll, setAnalyzingAll] = useState(false);
    const [analyzeProgress, setAnalyzeProgress] = useState('');
    const navigate = useNavigate();

    // --- Google Calendar Export ---
    const [isExportingCalendar, setIsExportingCalendar] = useState(false);
    const [calendarSuccess, setCalendarSuccess] = useState('');
    const [calendarError, setCalendarError] = useState('');

    const pushTasksToCalendar = async (accessToken) => {
        setIsExportingCalendar(true);
        setCalendarError('');
        setCalendarSuccess('');
        try {
            const startDate = new Date();
            let addedCount = 0;

            for (let weekIndex = 0; weekIndex < (planData?.roadmap || []).length; weekIndex++) {
                const weekObj = planData.roadmap[weekIndex];
                const weekStartDate = new Date(startDate);
                weekStartDate.setDate(weekStartDate.getDate() + (weekIndex * 7));

                for (let taskIndex = 0; taskIndex < (weekObj.tasks || []).length; taskIndex++) {
                    const task = weekObj.tasks[taskIndex];
                    const taskDate = new Date(weekStartDate);
                    taskDate.setDate(taskDate.getDate() + (taskIndex * 2));
                    taskDate.setHours(9, 0, 0, 0);
                    const endDate = new Date(taskDate);
                    endDate.setHours(10, 0, 0, 0);

                    const event = {
                        summary: `🚀 [Cmpny] ${task.title}`,
                        description: `Theme: ${weekObj.theme}\nPriority: ${task.priority}\nOwner: ${task.owner}\nGenerated by Compy AI.`,
                        start: { dateTime: taskDate.toISOString(), timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone },
                        end: { dateTime: endDate.toISOString(), timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone },
                    };

                    await fetch('https://www.googleapis.com/calendar/v3/calendars/primary/events', {
                        method: 'POST',
                        headers: {
                            'Authorization': `Bearer ${accessToken}`,
                            'Content-Type': 'application/json',
                        },
                        body: JSON.stringify(event)
                    });
                    addedCount++;
                }
            }
            setCalendarSuccess(`Successfully synced ${addedCount} tasks to your Google Calendar!`);
            setTimeout(() => setCalendarSuccess(''), 8000);
        } catch (error) {
            console.error('Calendar sync failed', error);
            setCalendarError('Failed to sync tasks to Google Calendar.');
        } finally {
            setIsExportingCalendar(false);
        }
    };

    const loginForCalendar = useGoogleLogin({
        onSuccess: (codeResponse) => pushTasksToCalendar(codeResponse.access_token),
        onError: (error) => setCalendarError('Google Login Failed.'),
        scope: 'https://www.googleapis.com/auth/calendar.events',
    });

    const readyCompetitors = competitors.filter((c) => c.status === 'crawled');
    const analysisData = analysisDataMap[activeCompetitorId] || null;
    const planData = planDataMap[activeCompetitorId] || null;

    const analyzedCount = readyCompetitors.filter((c) => !!analysisDataMap[c.id]).length;
    const pendingCount = readyCompetitors.length - analyzedCount;

    const handleAnalyze = async (compId) => {
        setAnalyzing(true);
        setAnalyzingId(compId);
        setError('');
        try {
            const result = await runAnalysis(compId);
            onAnalysisComplete(compId, result);
        } catch (err) {
            setError(err.message || 'Analysis failed');
        } finally {
            setAnalyzing(false);
            setAnalyzingId(null);
        }
    };

    const handleAnalyzeAll = async () => {
        setAnalyzingAll(true);
        setError('');
        const pending = readyCompetitors.filter((c) => !analysisDataMap[c.id]);
        for (let i = 0; i < pending.length; i++) {
            const comp = pending[i];
            setAnalyzeProgress(`Analyzing ${comp.name || comp.url} (${i + 1}/${pending.length})...`);
            setAnalyzingId(comp.id);
            onSelectCompetitor(comp.id);
            try {
                const result = await runAnalysis(comp.id);
                onAnalysisComplete(comp.id, result);
            } catch (err) {
                setError(`Failed on ${comp.name || comp.url}: ${err.message}`);
                break;
            }
        }
        setAnalyzingAll(false);
        setAnalyzingId(null);
        setAnalyzeProgress('');
    };

    const handlePlan = async () => {
        if (!activeCompetitorId) return;
        setPlanning(true);
        setError('');
        try {
            const result = await generatePlan(activeCompetitorId);
            onPlanComplete(activeCompetitorId, result);
        } catch (err) {
            setError(err.message || 'Planning failed');
        } finally {
            setPlanning(false);
        }
    };

    const getScoreColor = (score) => {
        if (score >= 80) return 'var(--accent-danger)';
        if (score >= 50) return 'var(--accent-warning)';
        return 'var(--accent-success)';
    };

    return (
        <div className="animate-fade-in-up">
            {/* Step Indicator */}
            <div className="steps">
                <div className="step completed">✅ 1. DNA</div>
                <div className="step-connector" />
                <div className="step completed">✅ 2. Scout</div>
                <div className="step-connector" />
                <div className="step active">🔬 3. Analyze</div>
                <div className="step-connector" />
                <div className="step">📊 4. Dashboard</div>
            </div>

            <h1 className="page-title">Intelligence Analysis</h1>
            <p className="page-subtitle">
                Run differential reasoning to extract threats, opportunities, and generate a tactical roadmap.
            </p>

            {/* All Competitors Overview */}
            <div className="glass-card--static" style={{ marginBottom: 'var(--space-xl)' }}>
                <div className="section-title">
                    🎯 Competitors ({analyzedCount}/{readyCompetitors.length} analyzed)
                </div>

                <div className="competitor-list">
                    {readyCompetitors.map((comp) => {
                        const hasAnalysis = !!analysisDataMap[comp.id];
                        const isAnalyzing = analyzingId === comp.id;
                        return (
                            <div
                                className={`competitor-row ${activeCompetitorId === comp.id ? 'active' : ''}`}
                                key={comp.id}
                                onClick={() => onSelectCompetitor(comp.id)}
                            >
                                <div className="competitor-row-info">
                                    <span className="competitor-row-name">{comp.name || comp.url}</span>
                                    <span className="competitor-row-url">{comp.url}</span>
                                </div>
                                <div className="competitor-row-meta">
                                    {isAnalyzing ? (
                                        <span className="badge" style={{ background: 'var(--accent-warning)', color: '#000' }}>
                                            <span className="loading-spinner" style={{ width: 12, height: 12, borderWidth: 2, marginRight: 4 }} />
                                            Analyzing...
                                        </span>
                                    ) : hasAnalysis ? (
                                        <span className="badge badge-opportunity">✅ Analyzed</span>
                                    ) : (
                                        <button
                                            className="btn btn-primary"
                                            style={{ padding: '4px 12px', fontSize: '0.8rem' }}
                                            onClick={(e) => { e.stopPropagation(); onSelectCompetitor(comp.id); handleAnalyze(comp.id); }}
                                            disabled={analyzing || analyzingAll}
                                        >
                                            ⚡ Analyze
                                        </button>
                                    )}
                                </div>
                            </div>
                        );
                    })}
                </div>

                {/* Analyze All Button */}
                {pendingCount > 0 && (
                    <div style={{ marginTop: 'var(--space-lg)', textAlign: 'center' }}>
                        {analyzingAll ? (
                            <div className="loading-state" style={{ gap: 'var(--space-sm)' }}>
                                <div className="loading-spinner" />
                                <p>{analyzeProgress}</p>
                            </div>
                        ) : (
                            <button
                                className="btn btn-primary btn-lg"
                                onClick={handleAnalyzeAll}
                                disabled={analyzing}
                                id="analyze-all-btn"
                            >
                                ⚡ Analyze All {pendingCount} Pending Competitor{pendingCount !== 1 ? 's' : ''}
                            </button>
                        )}
                    </div>
                )}

                {/* All done → go to dashboard */}
                {pendingCount === 0 && analyzedCount > 0 && !analyzingAll && (
                    <div style={{ marginTop: 'var(--space-lg)', textAlign: 'center' }}>
                        <p style={{ color: 'var(--accent-success)', marginBottom: 'var(--space-sm)', fontWeight: 600 }}>
                            ✅ All {analyzedCount} competitors analyzed!
                        </p>
                        <button className="btn btn-success btn-lg" onClick={() => navigate('/dashboard')} id="go-to-dashboard-from-analysis">
                            📊 View Dashboard →
                        </button>
                    </div>
                )}
            </div>

            {error && (
                <div className="glass-card--static" style={{ borderColor: 'var(--accent-danger)', marginBottom: 'var(--space-lg)' }}>
                    <p style={{ color: 'var(--accent-danger)' }}>❌ {error}</p>
                </div>
            )}

            {/* Analysis Results for selected competitor */}
            {analysisData && (
                <div className="animate-fade-in-up">
                    <div className="section-title" style={{ marginTop: 'var(--space-lg)' }}>
                        ⚡ Intelligence Report — {analysisData.competitor_name}
                    </div>

                    {/* Executive Summary */}
                    <div className="glass-card" style={{ marginBottom: 'var(--space-xl)', borderLeft: '4px solid var(--accent-primary)' }}>
                        <h3 style={{ fontSize: '1.2rem', marginBottom: 'var(--space-sm)' }}>Executive Summary</h3>
                        <p style={{ color: 'var(--text-secondary)', lineHeight: 1.6 }}>{analysisData.executive_summary}</p>
                    </div>

                    <div className="grid-2" style={{ marginBottom: 'var(--space-xl)' }}>
                        {/* Threats */}
                        <div className="glass-card--static">
                            <h3 style={{ color: 'var(--accent-danger)', marginBottom: 'var(--space-md)' }}>⚠️ Critical Threats</h3>
                            <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-md)' }}>
                                {(analysisData.signals?.threats || []).map((threat, i) => (
                                    <div key={i} style={{ paddingBottom: 'var(--space-sm)', borderBottom: '1px solid var(--border-color)' }}>
                                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 }}>
                                            <strong style={{ fontSize: '0.95rem' }}>{threat.title}</strong>
                                            <span className="badge" style={{ background: getScoreColor(threat.severity_score), color: '#000' }}>
                                                Sev: {threat.severity_score}
                                            </span>
                                        </div>
                                        <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginBottom: 8 }}>{threat.description}</p>
                                        {threat.evidence?.[0] && (
                                            <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', fontStyle: 'italic', borderLeft: '2px solid rgba(255,255,255,0.1)', paddingLeft: 8 }}>
                                                "{threat.evidence[0]}"
                                            </div>
                                        )}
                                    </div>
                                ))}
                            </div>
                        </div>

                        {/* Opportunities */}
                        <div className="glass-card--static">
                            <h3 style={{ color: 'var(--accent-success)', marginBottom: 'var(--space-md)' }}>🟢 Strategic Opportunities</h3>
                            <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-md)' }}>
                                {(analysisData.signals?.opportunities || []).map((opp, i) => (
                                    <div key={i} style={{ paddingBottom: 'var(--space-sm)', borderBottom: '1px solid var(--border-color)' }}>
                                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 }}>
                                            <strong style={{ fontSize: '0.95rem' }}>{opp.title}</strong>
                                            <span className="badge badge-opportunity">{opp.opportunity_type}</span>
                                        </div>
                                        <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginBottom: 8 }}>{opp.description}</p>
                                        {opp.evidence?.[0] && (
                                            <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', fontStyle: 'italic', borderLeft: '2px solid rgba(255,255,255,0.1)', paddingLeft: 8 }}>
                                                "{opp.evidence[0]}"
                                            </div>
                                        )}
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>

                    {/* Marketing Vs Reality */}
                    {analysisData.marketing_vs_reality_gaps?.length > 0 && (
                        <div className="glass-card--static" style={{ marginBottom: 'var(--space-xl)' }}>
                            <div className="section-title">🎭 Marketing vs Reality Gaps</div>
                            <div className="grid-2">
                                {analysisData.marketing_vs_reality_gaps.map((gap, i) => (
                                    <div key={i} className="glass-card" style={{ padding: 'var(--space-md)' }}>
                                        <div style={{ color: 'var(--accent-warning)', fontSize: '0.8rem', fontWeight: 700, textTransform: 'uppercase', marginBottom: 4 }}>Claim</div>
                                        <p style={{ fontSize: '0.9rem', marginBottom: 'var(--space-md)', color: 'var(--text-primary)' }}>"{gap.claim}"</p>
                                        <div style={{ color: 'var(--accent-primary)', fontSize: '0.8rem', fontWeight: 700, textTransform: 'uppercase', marginBottom: 4 }}>Reality</div>
                                        <p style={{ fontSize: '0.9rem', color: 'var(--text-secondary)' }}>{gap.reality}</p>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}

                    {/* Generate Plan Button */}
                    {!planData && (
                        <div style={{ marginTop: 'var(--space-xl)', textAlign: 'center' }}>
                            {planning ? (
                                <div className="loading-state">
                                    <div className="loading-spinner" />
                                    <p>Generating 4-week tactical roadmap...</p>
                                </div>
                            ) : (
                                <button className="btn btn-success btn-lg" onClick={handlePlan} id="generate-plan-btn">
                                    📋 Generate Tactical Roadmap
                                </button>
                            )}
                        </div>
                    )}

                    {/* Plan Results */}
                    {planData && (
                        <div className="animate-fade-in-up" style={{ marginTop: 'var(--space-xl)' }}>
                            <div className="section-title">📋 4-Week Tactical Roadmap</div>

                            <div className="timeline">
                                {(planData.roadmap || []).map((week, i) => (
                                    <div className="timeline-week" key={i}>
                                        <div className="timeline-week-header">
                                            <span className="timeline-week-label">Week {week.week}</span>
                                            <span className="timeline-week-theme">{week.theme}</span>
                                        </div>
                                        <div className="timeline-tasks">
                                            {(week.tasks || []).map((task, j) => (
                                                <div className="timeline-task" key={j}>
                                                    <div className="timeline-task-header">
                                                        <span className="timeline-task-title">{task.title}</span>
                                                        <span className={`badge badge-${task.task_type}`}>{task.task_type}</span>
                                                    </div>
                                                    <p style={{ fontSize: '0.825rem', color: 'var(--text-secondary)', marginBottom: 'var(--space-xs)' }}>
                                                        {task.description}
                                                    </p>
                                                    <div className="timeline-task-meta">
                                                        <span>👤 {task.owner}</span>
                                                        <span>•</span>
                                                        <span style={{ color: task.priority === 'critical' ? 'var(--accent-danger)' : 'var(--text-muted)' }}>
                                                            {task.priority}
                                                        </span>
                                                        <span>•</span>
                                                        <span>📏 {task.success_metric}</span>
                                                    </div>
                                                </div>
                                            ))}
                                        </div>
                                    </div>
                                ))}
                            </div>

                            {/* Google Calendar CTA */}
                            <div style={{ marginTop: 'var(--space-xl)', textAlign: 'center', borderTop: '1px solid rgba(255,255,255,0.05)', paddingTop: 'var(--space-md)' }}>
                                <p style={{ color: 'var(--text-secondary)', fontSize: '0.85rem', marginBottom: 'var(--space-sm)' }}>
                                    Automatically schedule this battle plan on your exact timeline.
                                </p>
                                <button
                                    className="btn btn-primary"
                                    onClick={() => loginForCalendar()}
                                    disabled={isExportingCalendar}
                                    style={{ backgroundColor: '#fff', color: '#000', borderColor: '#fff' }}
                                >
                                    {isExportingCalendar ? (
                                        <><span className="loading-spinner" style={{ width: 14, height: 14, borderWidth: 2, borderColor: '#000', borderTopColor: 'transparent' }} /> Syncing to Calendar...</>
                                    ) : (
                                        <>📅 Sync to Google Calendar</>
                                    )}
                                </button>
                                {calendarError && <p style={{ color: 'var(--accent-danger)', fontSize: '0.85rem', marginTop: 'var(--space-sm)' }}>❌ {calendarError}</p>}
                                {calendarSuccess && <p style={{ color: 'var(--accent-success)', fontSize: '0.85rem', marginTop: 'var(--space-sm)' }}>✅ {calendarSuccess}</p>}
                            </div>

                            <div style={{ marginTop: 'var(--space-xl)', textAlign: 'center' }}>
                                <button
                                    className="btn btn-primary btn-lg"
                                    onClick={() => navigate('/dashboard')}
                                    id="go-to-dashboard-btn"
                                >
                                    📊 View Full Dashboard →
                                </button>
                            </div>
                        </div>
                    )}
                </div>
            )}
        </div>
    );
}
